# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ContactMvvmExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'pop'
  pod 'Kingfisher', '~> 4.10.1'
  pod 'Networking', '~> 4.1.1'

  
  # Pods for ContactMvvmExample
  target 'ContactMvvmExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
  target 'ContactMvvmExampleUITests' do
    # Pods for testing
  end
end
